#!/bin/bash
#PBS -l select=2:ncpus=8:mem=20GB
#PBS -P PROJECT_NAME
#PBS -q serial
#PBS -l walltime=4:00:00
#PBS -o OUTPUT_FILE_PBS
#PBS -e ERROR_FILE_PBS
#PBS -m abe
#PBS -M PBS_EMAIL

#kill execution at first error
set -euox pipefail 

#for evaluating variables in ~/.pbsrc
source ~/.pbsrc

#resource parameters
THREADS=8

#directories and files
WORKDIR="${TOMATO_PATH}/SAMPLE_CLI"
RAW_READS_FQ="${WORKDIR}/raw_reads/SAMPLE_CLI.fastq"
ALL_RESULTS_DIR="${workdir}/results"
JELLYFISH_OUT_DIR="RESULTS_DIR"
JELLYFISH_JF="${JELLYFISH_OUT_DIR}/SAMPLE_CLI.jf"
JELLYFISH_HISTO="${JELLYFISH_OUT_DIR}/SAMPLE_CLI.histo"

#load modules
module load chpc/BIOMODULES
module load jellyfish/2.2.10 

#jellyfish kmer analysis
jellyfish count -m 21 -s 100M -t ${THREADS} -C -o ${JELLYFISH_JF} ${RAW_READS_FQ}

#jellyfish histogram construction
jellyfish histo -t ${THREADS} ${JELLYFISH_JF} > ${JELLYFISH_HISTO}
