#!/bin/bash
#PBS -l select=2:ncpus=8:mem=20GB
#PBS -P PROJECT_NAME
#PBS -q serial
#PBS -l walltime=4:00:00
#PBS -o GRAPEVINE_PATH_PBS/palo_mino/results/01.jellyfish/run_1.out
#PBS -e GRAPEVINE_PATH_PBS/palo_mino/results/01.jellyfish/run_1.err
#PBS -m abe
#PBS -M PBS_EMAIL

#kill execution at first error
set -euox pipefail 

#for evaluating variables in ~/.pbsrc
source ~/.pbsrc

#resource parameters
THREADS=8

#directories and files
workdir="${GRAPEVINE_PATH}/palo_mino"
raw_reads_fq="${workdir}/raw_reads/palo_mino.fastq"
all_results_dir="${workdir}/results"
jellyfish_jf="${all_results_dir}/01.jellyfish/palo_mino.jf"
jellyfish_histo="${all_results_dir}/01.jellyfish/palo_mino.histo"

#jellyfish kmer analysis
jellyfish count -m 21 -s 100M -t ${THREADS} -C -o ${jellyfish_jf} ${raw_reads_fq}

#jellyfish histogram construction
jellyfish histo -t ${THREADS} ${jellyfish_jf} > ${jellyfish_histo}
