#!/bin/bash
#PBS -l select=2:ncpus=8:mem=20GB
#PBS -P PROJECT_NAME
#PBS -q serial
#PBS -l walltime=4:00:00
#PBS -o OUTPUT_FILE_PBS
#PBS -e ERROR_FILE_PBS
#PBS -m abe
#PBS -M PBS_EMAIL

#kill execution at first error
set -euox pipefail 

#for evaluating variables in ~/.pbsrc
source ~/.pbsrc

#resource parameters
THREADS=8

#directories and files
workdir="${TOMATO_PATH}/SAMPLE_CLI"
raw_reads_fq="${workdir}/raw_reads/SAMPLE_CLI.fastq"
all_results_dir="${workdir}/results"
jellyfish_out_dir="RESULTS_DIR"
jellyfish_jf="${jellyfish_out_dir}/SAMPLE_CLI.jf"
jellyfish_histo="${jellyfish_out_dir}/SAMPLE_CLI.histo"

#load modules
module load chpc/BIOMODULES
module load jellyfish/2.2.10 

#jellyfish kmer analysis
jellyfish count -m 21 -s 100M -t ${THREADS} -C -o ${jellyfish_jf} ${raw_reads_fq}

#jellyfish histogram construction
jellyfish histo -t ${THREADS} ${jellyfish_jf} > ${jellyfish_histo}
