#!/bin/bash
#PBS -l select=1:ncpus=16:mem=60GB
#PBS -P PROJECT_NAME
#PBS -q serial
#PBS -l walltime=48:00:00
#PBS -o GRAPEVINE_PATH_PBS/SAMPLE_CLI/results/04.busco_hifiasm/busco_hifiasm.out
#PBS -e GRAPEVINE_PATH_PBS/SAMPLE_CLI/results/04.busco_hifiasm/busco_hifiasm.err
#PBS -m be
#PBS -M PBS_EMAIL

#kill execution at first error
set -euox pipefail 

#for evaluating variables in ~/.pbsrc
source ~/.pbsrc

#resource parameters
THREADS=16

#directories and files
workdir="${GRAPEVINE_PATH}/SAMPLE_CLI"
all_results_dir="${workdir}/results"
busco_dir="${all_results_dir}/03.1.busco_hifiasm"
busco_db_dir="/mnt/lustre/users/nnkiwane/masters/databases"
contigs_dir="${all_results_dir}/contigs"
contigs_in="${contigs_dir}/SAMPLE_CLI_hap?.fa"

#load modules
module load chpc/BIOMODULES
module load busco/6.0.0

#check quality of assembled contigs for each haplotype
for fasta in ${contigs_in};do
    singularity run $SIF busco --in ${fasta} \
    --metaeuk \
    -m genome \
    -l eudicotyledons_odb12 \
    --download_path ${busco_db_dir} \
    -c ${THREADS} \
    --out_path ${busco_dir};
done