#!/bin/bash
#PBS -l select=2:ncpus=8:mem=60GB
#PBS -P PROJECT_NAME
#PBS -q serial
#PBS -l walltime=48:00:00
#PBS -o GRAPEVINE_PATH_PBS/SAMPLE_CLI/results/03.hifiasm/hifiasm.out
#PBS -e GRAPEVINE_PATH_PBS/SAMPLE_CLI/results/03.hifiasm/hifiasm.err
#PBS -m be
#PBS -M PBS_EMAIL

#kill execution at first error
set -euox pipefail 

#for evaluating variables in ~/.pbsrc
source ~/.pbsrc

#resource parameters
THREADS=8

#directories and files
workdir="${GRAPEVINE_PATH}/${SAMPLE_CLI}"
raw_reads_fq="${workdir}/raw_reads/${SAMPLE_CLI}.fastq"
all_results_dir="${workdir}/results"
hifiasm_asm="${all_results_dir}/03.hifiasm/${SAMPLE_CLI}.asm"


#load modules
module load chpc/BIOMODULES
module load hifiasm/0.24.0-r703

#hifiasm assembly
hifiasm -o ${hifiasm_asm} -t ${THREADS} ${raw_reads_fq}
