#!/bin/bash
#PBS -l select=1:ncpus=23:mem=60GB
#PBS -P PROJECT_NAME
#PBS -q serial
#PBS -l walltime=48:00:00
#PBS -o OUTPUT_FILE_PBS
#PBS -e ERROR_FILE_PBS
#PBS -m be
#PBS -M PBS_EMAIL

#kill execution at first error
set -euox pipefail 

#for evaluating variables in ~/.pbsrc
source ~/.pbsrc

#resource parameters
THREADS=16

#directories and files
workdir="${GRAPEVINE_PATH}/SAMPLE_CLI"
raw_reads_fq="${workdir}/raw_reads/SAMPLE_CLI.fastq"
all_results_dir="${workdir}/results"
hifiasm_dir="RESULTS_DIR"
hifiasm_asm="${hifiasm_dir}/SAMPLE_CLI.asm"
gfa_files="${hifiasm_dir}/SAMPLE_CLI.asm.bp.hap?.p_ctg.gfa"
contigs_dir="${all_results_dir}/contigs"

#load modules
module load chpc/BIOMODULES
module load hifiasm/0.24.0-r703
module load gzip-1.9

#hifiasm assembly
echo "Performing contig assembly..."
hifiasm -o ${hifiasm_asm} -t ${THREADS} ${raw_reads_fq} || { echo "Contig assembly failed"; exit 1; }
echo "Contig assembly complete"

#convert gfa to fasta
for gfa in ${gfa_files}; do
    echo "Extracting contigs for ${gfa}..."

    #extract basename to name output fasta file
    hap=$(basename ${gfa} | grep -o "hap[0-9]")
    fasta_out="${contigs_dir}/SAMPLE_CLI_${hap}.fa"

    #extract sequences from gfa to fasta
    awk '/^S/{print ">"$2; print $3}' "${gfa}" > ${fasta_out} || { echo "Contig extraction failed for ${gfa}"; exit 1; }
    echo "Contig extraction complete."

    #compress fasta files
    echo "Compressing fasta files..."
    gzip -k ${fasta_out} || { echo "Fasta compression failed for ${fasta_out}"; exit 1; }
    echo "Fasta compression complete"
done
