#!/bin/bash
#PBS -l select=2:ncpus=25:mem=60GB
#PBS -P PROJECT_NAME
#PBS -q normal
#PBS -l walltime=48:00:00
#PBS -o OUTPUT_FILE_PBS
#PBS -e ERROR_FILE_PBS
#PBS -m be
#PBS -M PBS_EMAIL

#kill execution at first error
set -euox pipefail 

#for evaluating variables in ~/.pbsrc
source ~/.pbsrc

#resource parameters
THREADS=23

#directories and files
workdir="${GRAPEVINE_PATH}/SAMPLE_CLI"
all_results_dir="${workdir}/results"
busco_dir="RESULTS_DIR"
busco_db_dir="/mnt/lustre/users/nnkiwane/masters/databases"
contigs_dir="${all_results_dir}/contigs"
contigs_in="${contigs_dir}/SAMPLE_CLI_hap?.fa"

#load modules
module load chpc/BIOMODULES
module load busco/6.0.0

#check quality of assembled contigs for each haplotype
RUN_BUSCO() {
    local fasta="${1}"
    singularity run $SIF busco --in ${fasta} \
    --metaeuk \
    -m genome \
    -l eudicotyledons_odb12 \
    --download_path ${busco_db_dir} \
    -c ${THREADS} \
    --out_path ${busco_dir}
}

for fasta in ${contigs_in};do
    echo "Running BUSCO for ${fasta}"
    RUN_BUSCO ${fasta}
    echo "BUSCO for ${fasta} complete";
done