#!/bin/bash
#PBS -l select=1:ncpus=23:mem=60GB
#PBS -P PROJECT_NAME
#PBS -q serial
#PBS -l walltime=48:00:00
#PBS -o OUTPUT_FILE_PBS
#PBS -e ERROR_FILE_PBS
#PBS -m be
#PBS -M PBS_EMAIL

#kill execution at first error
set -euox pipefail 

#for evaluating variables in ~/.pbsrc
source ~/.pbsrc

#directories and files
workdir="${GRAPEVINE_PATH}/SAMPLE_CLI"
raw_reads_gz="${workdir}/raw_reads/SAMPLE_CLI.fastq.gz"
merqury_dir="RESULTS_DIR"
meryl_output="${merqury_dir}/SAMPLE_CLI_asm.meryl"
all_results_dir="${workdir}/results"
contigs_dir="${all_results_dir}/contigs"
contigs_in_1="${contigs_dir}/SAMPLE_CLI_hap1.fa.gz"
contigs_in_2="${contigs_dir}/SAMPLE_CLI_hap2.fa.gz"
merqury_out_prefix="mq_SAMPLE_CLI"

#check if non-empty files exist
for FILE in ${raw_reads_gz} ${contigs_in_1} ${contigs_in_2}; do
    if [[ ! -s ${FILE} ]]; then
        echo "ERROR: File empty or missing: ${FILE}"
        exit 1
    fi
done

#check if meryl database for reads made
if [[ ! -d ${meryl_output} ]]; then
    echo "ERROR: Meryl database empty or missing: ${meryl_output}"
    exit 1
fi


#load modules
module load chpc/BIOMODULES
module load merqury

#run merqury to check quality of assembled contigs for each haplotype
echo "Running merqury on assembled contigs "
cd ${merqury_dir}
singularity run $SIF merqury.sh ${meryl_output} ${contigs_in_1} ${contigs_in_2} ${merqury_out_prefix}
echo "Merqury complete"