#!/bin/bash
#PBS -l select=1:ncpus=23:mem=60GB
#PBS -P PROJECT_NAME
#PBS -q serial
#PBS -l walltime=48:00:00
#PBS -o OUTPUT_FILE_PBS
#PBS -e ERROR_FILE_PBS
#PBS -m be
#PBS -M PBS_EMAIL

#kill execution at first error
set -euox pipefail 

#for evaluating variables in ~/.pbsrc
source ~/.pbsrc

#parameters
THREADS=23
MEMORY=60
kmer_size=31

#directories and files
workdir="${GRAPEVINE_PATH}/SAMPLE_CLI"
raw_reads="${workdir}/raw_reads/SAMPLE_CLI.fastq"
raw_reads_gz="${workdir}/raw_reads/SAMPLE_CLI.fastq.gz"
merqury_dir="RESULTS_DIR"
meryl_output="${merqury_dir}/SAMPLE_CLI_asm.meryl"
all_results_dir="${workdir}/results"
contigs_dir="${all_results_dir}/contigs"
contigs_in_1="${contigs_dir}/SAMPLE_CLI_hap1.fa.gz"
contigs_in_2="${contigs_dir}/SAMPLE_CLI_hap2.fa.gz"
merqury_out_prefix="mq_"

#check if non-empty files exist
for FILE in ${raw_reads} ${contigs_in_1} ${contigs_in_2}; do
    if [[ ! -s ${FILE} ]]; then
        echo "ERROR: File empty or missing: ${FILE}"
        exit 1
    fi
done

#load modules
module load chpc/BIOMODULES
module load merqury

# >>> run on first run only >>>

# #compress raw read files
# gzip ${raw_reads}

#make reads.meryl database
echo "Performing k-mer count on raw reads for reads.meryl database"
meryl count k=${kmer_size} threads=${THREADS} memory=${MEMORY} ${raw_reads_gz} output ${meryl_output} 
echo "Reads database successfully made"

# <<< run on first run only <<<

#run merqury to check quality of assembled contigs for each haplotype
echo "Running merqury on assembled contigs "
singularity run $SIF merqury.sh ${meryl_output} ${contigs_in_1} ${contigs_in_2} ${merqury_out_prefix}
echo "Merqury complete"