#!/bin/bash
#PBS -l select=1:ncpus=24:mem=124GB
#PBS -P PROJECT_NAME
#PBS -q normal
#PBS -l walltime=4:00:00
#PBS -o GRAPEVINE_PATH/palo_mino/results/04.hifiasm/run_1.out
#PBS -e GRAPEVINE_PATH/palo_mino/results/04.hifiasm/run_1.err
#PBS -m abe
#PBS -M PBS_EMAIL

#kill execution at first error
set -euox pipefail 

#resource parameters
THREADS=24

#directories and files
workdir="/mnt/lustre/users/nnkiwane/masters/grapevine/palo_mino"
raw_reads_fq="${workdir}/raw_reads/palo_mino.fastq"
all_results_dir="${workdir}/results"
hifiasm_asm="${all_results_dir}/04.hifiasm/palo_mino.asm"

#hifiasm assembly
hifiasm -o ${hifiasm_asm} -t ${THREADS} ${raw_reads_fq}
