#!/bin/bash
#PBS -l select=2:ncpus=8:mem=60GB
#PBS -P PROJECT_NAME
#PBS -q serial
#PBS -l walltime=8:00:00
#PBS -o GRAPEVINE_PATH_PBS/palo_mino/results/04.hifiasm/run_1.out
#PBS -e GRAPEVINE_PATH_PBS/palo_mino/results/04.hifiasm/run_1.err
#PBS -m be
#PBS -M PBS_EMAIL

#kill execution at first error
set -euox pipefail 

#for evaluating variables in ~/.pbsrc
source ~/.pbsrc

#resource parameters
THREADS=8

#directories and files
workdir="${GRAPEVINE_PATH}/palo_mino"
raw_reads_fq="${workdir}/raw_reads/palo_mino.fastq"
all_results_dir="${workdir}/results"
hifiasm_asm="${all_results_dir}/04.hifiasm/palo_mino.asm"

#load modules
module load chpc/BIOMODULES
module load hifiasm/0.24.0-r703

#hifiasm assembly
hifiasm -o ${hifiasm_asm} --primary -t ${THREADS} ${raw_reads_fq}
